@plr = player()



@hero = associative_array(
            'name': '§2R§5i§2d§2d§5l§5e§2r',
            'class': 'Riddler',
            'sig': 'vr+VvfcrVaMLczcWWA+W4+riHtTJMDBa1n16b0U4poY29f60mciaV4lYQFTpVKAN68UsDKVHoc3VL4sdn/J2O9JzMgjPzERcLCkt3rOnWxKaQKlwF60mIHr01ppeupe9SsmBTkOnaPZ1EJbXYiQQCWmn3A5MPBJlZPfp/sF27d6qvutklumKjZpPBNXCKUREmrdi2XJi59DmvZx494V+2zwyJ/rx1eVqM6YmeIXL90kI+Y/sTH5tBRxscQ1A/0E/CnBsredAQbjlM1eRKRCVfdDu2OA06CtKjTKdpkacfqIn+HewNYkyRmpWNBjGccVRbVUG+15kAWb9DJGisbRr4AtJvMQz7oQk1Vnf4RNhWdhMbTQ23KW7K8V44Yl5e4/5LvIA65gClvc7vzKZDK7lUd/uIamnNidnnZ8LQ3vhTmwRcyHSQXlHpbrKv78EUrWh9C3cU0uwhh9FePXWbxvABZswL8KaZ2u1iBKegvBoHlOAakxPtIxmKmFEsCXEpAKFyrpzVMSBE4Ydy2nZgJsh8hk0egTfaFpVsJmj5YYa0a5SsI/ZWkAUVulZHLxbs29J8yrHbIh/XQQ/eNHAtRzdLyzwAElFpgYRvLmWDjVwUVoQS5B0wu4AwcMv3holdMkBGzfD3mKm6p1L6WdwhKmwB/t2h7/clYMSheknzNR7CHY=',
            'val': 'eyJ0aW1lc3RhbXAiOjE1MDE3MTg0MTcyMTAsInByb2ZpbGVJZCI6IjcxNjA5Y2JmYzQ5NzQ4Njk4NWZlNjllNDZmYmZjNzFlIiwicHJvZmlsZU5hbWUiOiJzdXBlcm1vbzEyIiwic2lnbmF0dXJlUmVxdWlyZWQiOnRydWUsInRleHR1cmVzIjp7IlNLSU4iOnsidXJsIjoiaHR0cDovL3RleHR1cmVzLm1pbmVjcmFmdC5uZXQvdGV4dHVyZS9iY2JhMjViOWE1MmVlZTE0NTZlODMyZGY4Nzc1NjhiODMyZGFiMjhkYzE0YWEwYmE4YTUyNjdmOTZhNjgzOCJ9fX0=',
            'trail': '',
            'op': 'false',
            'speech': "Do you Like Riddles?",
            'powers': array(
                "/buff",
                "/run 0-1"
            ),
            'buffs': array(
                "/effect ".@plr." 5 9999 1 true",
                "/effect ".@plr." 21 9999 2 true",
25             "/give ". @plr ." minecraft:stick 1 20:2 name: §2R§5idder's Cane",
                "/give ". @plr ." minecraft:Paper 1  name:list o' Riddles"
            )
        )
